# Generated by Django 5.0 on 2023-12-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('placa', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('hora_entrada', models.DateField(auto_now_add=True)),
                ('hora_saida', models.DateField(null=True)),
                ('tipo', models.CharField(max_length=5)),
            ],
        ),
    ]
