# Generated by Django 5.0 on 2023-12-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('placa', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('andar', models.CharField(choices=[('Andar 1', 'Andar 1'), ('Andar 2', 'Andar2')], max_length=8, null=True)),
                ('hora_entrada', models.TimeField(auto_now_add=True)),
                ('hora_saida', models.TimeField(null=True)),
                ('tipo', models.CharField(choices=[('Motocicleta', 'Motocicleta'), ('Carro', 'Carro')], max_length=11)),
                ('valor', models.IntegerField(null=True)),
            ],
        ),
    ]
